"""
Stage 5: Apply the fix + draft a PR
---------------------------------------
Runs the Stage 4 agent to get a proposed fix, then:
  1. VERIFIES the original_code the model claims it saw still actually
     exists in the real file (catches the model paraphrasing instead of
     copying exactly - a real failure mode, not a hypothetical one).
  2. Shows a unified diff and asks for your confirmation before writing
     anything.
  3. Writes the fix to disk.
  4. Drafts a PR title/description as a markdown file.
  5. Optionally (only with --git) creates a branch and commits locally -
     it NEVER pushes. You always get the final look before anything
     leaves your machine.

Design decision: verify-before-write.
An LLM can be confidently wrong about what code it "saw" - it's
generating tokens, not literally quoting a buffer. If original_code
doesn't match the real file, writing fixed_code anyway could silently
corrupt the file (e.g. if it matched the wrong function, or half-quoted
a snippet). This check turns a silent corruption into a loud refusal.

Design decision: confirm, then write - never auto-apply.
The one thing worse than an agent that can't fix bugs is one that fixes
the WRONG thing without asking. Every step past the confirmation prompt
is deterministic and reviewable - there's no "trust me" step.

Design decision: commit locally at most, never push.
Even with --git, this stops at a local commit. Pushing is a genuinely
different action - it can trigger CI, notify teammates, open a PR
automatically. That should always be a deliberate, separate command you
run yourself, not something a script did on your behalf.

Usage:
    python apply_fix.py "add_item seems to remember items between calls"
    python apply_fix.py "malicious user_id crashes the app" --git
"""

import argparse
import datetime
import difflib
import os
import subprocess
import sys

from agent import setup, run_agent, print_transcript, print_fix


def find_original_in_file(file_path: str, original_code: str):
    """Return True if original_code (whitespace-normalized) is actually
    present in the file on disk right now."""
    if not os.path.isfile(file_path):
        return False
    with open(file_path, "r", encoding="utf-8") as f:
        file_content = f.read()

    def normalize(s):
        return "\n".join(line.rstrip() for line in s.strip().splitlines())

    return normalize(original_code) in normalize(file_content)


def apply_replacement(file_path: str, original_code: str, fixed_code: str):
    with open(file_path, "r", encoding="utf-8") as f:
        content = f.read()

    def normalize(s):
        return "\n".join(line.rstrip() for line in s.strip().splitlines())

    norm_content = normalize(content)
    norm_original = normalize(original_code)

    if norm_original not in norm_content:
        raise ValueError("original_code no longer matches the file (it may have changed).")

    new_content = norm_content.replace(norm_original, fixed_code.strip(), 1)
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(new_content)


def show_diff(original_code: str, fixed_code: str, file_path: str):
    diff = difflib.unified_diff(
        original_code.strip().splitlines(keepends=True),
        fixed_code.strip().splitlines(keepends=True),
        fromfile=f"{file_path} (original)",
        tofile=f"{file_path} (proposed)",
    )
    print("\n" + "".join(diff))


def draft_pr_description(fix: dict, bug_description: str) -> str:
    title = f"Fix {fix['symbol']}: address reported issue"
    body = f"""## Summary

{fix['explanation']}

## Bug report

> {bug_description}

## Change

**File:** `{fix['file']}`
**Symbol:** `{fix['symbol']}`
**Agent confidence:** {fix['confidence']}

### Before
```python
{fix['original_code'].strip()}
```

### After
```python
{fix['fixed_code'].strip()}
```

## Review notes

This fix was proposed and applied by an autonomous agent (Stage 4/5 of this
project) after investigating the codebase via hybrid search. It has **not**
been tested beyond the agent's own reasoning - please review the diff and
run the project's tests (or add one) before merging.

---
*Generated by agent.py + apply_fix.py*
"""
    return f"# {title}\n\n{body}"


def git_commit_on_branch(file_path: str, symbol: str, title: str):
    timestamp = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
    branch_name = f"fix/{symbol}-{timestamp}"
    try:
        subprocess.run(["git", "checkout", "-b", branch_name], check=True)
        subprocess.run(["git", "add", file_path], check=True)
        subprocess.run(["git", "commit", "-m", title], check=True)
        print(f"\nCommitted locally on branch '{branch_name}'. "
              f"Nothing has been pushed - review with 'git show', then push yourself when ready.")
    except subprocess.CalledProcessError as e:
        print(f"\nGit step failed: {e}. The file was still written/modified on disk - "
              f"handle git manually if needed.")


def main():
    parser = argparse.ArgumentParser(description="Investigate a bug, propose a fix, and apply it (with confirmation).")
    parser.add_argument("bug_description", help="Plain-English bug description, in quotes.")
    parser.add_argument("--max-steps", type=int, default=6)
    parser.add_argument("--git", action="store_true", help="Also create a branch and commit locally (never pushes).")
    parser.add_argument("--yes", action="store_true", help="Skip the confirmation prompt (use with care).")
    args = parser.parse_args()

    client, collection, bm25, chunks = setup()
    fix, transcript = run_agent(client, collection, bm25, chunks, args.bug_description, args.max_steps)

    print_transcript(transcript)
    if not fix:
        print("\nAgent did not produce a fix - nothing to apply.")
        sys.exit(1)

    print_fix(fix)

    if not find_original_in_file(fix["file"], fix["original_code"]):
        print(f"\nSAFETY CHECK FAILED: the code the agent thinks it saw does not match "
              f"what's actually in {fix['file']} right now. Refusing to write - the model "
              f"may have paraphrased instead of copying the code exactly. Nothing was changed.")
        sys.exit(1)

    print("\nSafety check passed: original_code confirmed present in the file.")
    show_diff(fix["original_code"], fix["fixed_code"], fix["file"])

    if not args.yes:
        answer = input("\nApply this fix to disk? [y/N]: ").strip().lower()
        if answer != "y":
            print("Not applied. Nothing was changed.")
            sys.exit(0)

    apply_replacement(fix["file"], fix["original_code"], fix["fixed_code"])
    print(f"\nApplied. {fix['file']} has been updated.")

    pr_text = draft_pr_description(fix, args.bug_description)
    pr_path = f"PR_{fix['symbol']}.md"
    with open(pr_path, "w", encoding="utf-8") as f:
        f.write(pr_text)
    print(f"PR description drafted at {pr_path}")

    if args.git:
        git_commit_on_branch(fix["file"], fix["symbol"], f"Fix {fix['symbol']}: address reported issue")


if __name__ == "__main__":
    main()
